[package]
name = "sphynx_rendering"
version = "0.1.0"
edition = "2021"

[dependencies]
sphynx_derive_vertex_attrib = { path = "../derive_vertex_attrib" }
winit = "0.29.15"
wgpu = "0.19.3"
pollster = "0.3.0"
anyhow = "1.0.81"
cgmath = "0.18"
bytemuck = { version = "1.15", features = ["derive"] }
